permalink: pretty
markdown: rdiscount
highlighter: pygments

url: http://dclegalhackers.org/networksofdc
baseurl: http://dclegalhackers.org/networksofdc
gems:
  - jekyll-redirect-from

collections:
  - networks

sass:
    sass_dir: assets/_sass
