permalink: pretty
markdown: rdiscount
highlighter: pygments

url: http://dclegalhackers.org/networksofdc
baseurl: http://dclegalhackers.org/networksofdc

collections:
  - plays

sass:
    sass_dir: assets/_sass
